# Jekyll configuration
encoding: 'utf-8'
name: PluckyMagnet
description: 哈哈

# Url is currently only used only for the RSS feed in feed.xml
url: http://pluckytyx.top/


# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: PluckySaltyfish
  qqemail:
  sina: '石见黑黑'
  instagram: 'PluckyTang'
  

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: Plucky
comments: true

permalink: /:year/:month/:title
plugins: [jekyll-paginate]
# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3
paginate: 8
paginate_path: "page:num"
#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
